### ISSUE TITLE
assertion fails in tpcc with high contention

### ISSUE THREAD

**Issue by shuaimu** [nathanielherman/sto#16]
Hi there, I really like this project and am trying to build something on top of it. In particular, I'm interested in the case where the workload has a lot of contention. To achieve this I ran the tpcc benchmark with only 1 warehouse on 24 cores. I found that an assert in the code is not passing. This issue is fully reproducible with the following command line, which is what I am using for compiling and running:

```
MODE=perf CXX=c++\ -std=gnu++0x make -j dbtest
out-perf.masstree/benchmarks/dbtest --runtime 30 --num-threads 24 --scale-factor 1 --bench tpcc -dmbta --retry-aborted-transactions --verbose
```
The failed assertion is in tpcc.cc:1838
```
ALWAYS_ASSERT(c_order_line.n >= 5 && c_order_line.n <= 15);
```

The same command line runs fine with the stock Silo. Thanks!

**Comment by huangyihe** [comment]
Thanks for noticing the bug! We've made some changes and please verify that the bug is now gone.

**Comment by shuaimu** [comment]
Thank you for the fix! It runs okay on my desktop now.
