### ISSUE TITLE
find_or_abort returning GRANDparent when key not found!

### ISSUE THREAD

**Issue by huangyihe** [nathanielherman/sto#7]
I found a couple very serious bugs:
1. `RBTreeInternal.hh`: In `find_any()`, we are actually returning the grandparent of the absent key... Took me almost the entire afternoon to figure out why `find_any()` and `insert()` returned different parents...
2. `RBTree.hh`: We forgot to unlock before we abort in `find_or_abort()`

Fixed in 7944322d5670fc717b63dda14aff69dff7616027 (on `rbtree_bn`)

**Comment by huangyihe** [comment]
Another bug: `count()`, `erase()`, and `find_or_abort()` not handling our new delete-my-insert scheme correctly.

**Comment by huangyihe** [comment]
I think I figured out why we are seeing "aborts" in `tester.check()` (the last step in our `trans_test`). It was an assertion failure (because we are returning non-existent `item.write_value()`s), but with `-O3` it sometimes shows up as a `Transaction::abort` exception.

Fixed in 39501f0f26c493f16e4d921bd2750fae152be353

**Comment by huangyihe** [comment]
Also I think `item.write_value` is not being installed in some insert-then-delete corner cases...

**Comment by huangyihe** [comment]
Fixed the issue mentioned in the comment above in 14f16669756ba230f993ae6f58cd99855258bbb2
The new test checked in in 604afdd4149bacdbf2c5d59bf03527f0104b2d5a exposes the issue.

**Comment by huangyihe** [comment]
I have a question:
If we can turn an update into a new insert at commit time (because another deleting transaction committed), we risk violating the strict serializability enforced by the test framework, right? (Since the test framework replays transactions in `commit_tid()` order.)

**Comment by tslilyai** [comment]
Dealt with the above in  [a68912d](https://github.com/nathanielherman/sto/commit/a68912d42ba579aa5eaae06b6f38375b0d8f9aa2)
if we found the item, this means that another transaction inserted another item with the same key. we should update it instead of reinsert

if the other transaction hasn't yet committed, we ignore the item and just insert it ourselves (the other transaction will do the update if it commits

**Comment by huangyihe** [comment]
Closed for now (fixed all self-aborting loop)
